### PR TITLE
Full Re-Design

### PR DESCRIPTION
**Pull request by VutonDesign**
A full re-design to your site as requested

## Features
- Your logo
- Your name
- Your bio
- Social icons

## Preview
http://vutondesign.com/redmangospros.github.io/

### CODE REVIEW

**Comment by redmangospros** [comment]
i acutully want it at thegittoro!

**Comment by VutonDesign** [comment]
@redmangospros Just delete ```thegittoro``` and rename this ```thegittoro```

**Comment by redmangospros** [comment]
And Can you Remove Your Favicon.
And Can you Help me t\with the pages just with css?

**Comment by VutonDesign** [comment]
@redmangospros My favicon isn't on it...

**Pull request merged**
